import React, { useState } from 'react'
import Page from '../../components/Page'
import clsx from 'clsx'
import * as style from './resources.module.sass'
import PageHeader from '../../components/PageHeader'
import { string } from 'yargs'

interface glossaryReferences {
	name: string
	link: string
}

interface glossaryArrayTermInterface {
	term: string
	def: string
	ref?: glossaryReferences[]
	aka?: string[]
}

const IndexPage = () => {
	const [filter, setFilter] = useState('')

	const handelInputChange = (e) => setFilter(e.target.value)

	const rootClassName: string = clsx([style.resourcesPage, 'resources-page'])

	const glossaryArray: glossaryArrayTermInterface[] = [
		{
			term: `Epistemology`,
			aka: [`epistemic`],
			def: `Epistemology (sometimes referred to as 'the theory of knowledge') is a branch of philosophy that studies of the nature, origin, and limits of human knowledge. The term is derived from the Greek epistēmē ("knowledge") and logos ("reason").`,
		},
		{
			term: `Interlocutor`,
			aka: [`IL`],
			def: `A person who takes part in a dialogue or conversation, sometimes called the conversation partner.`,
		},
		{
			term: `Rhetoric`,
			def: `The art of persuasion, which along with grammar and logic, is one of the three ancient arts of discourse. Rhetoric aims to study the techniques writers or speakers utilize to inform, persuade, or motivate particular audiences in specific situations.`,
		},
		{
			term: `How to have Impossible Conversations`,
			aka: [`HoHIC`],
			def: `'A Manual for Creating Atheists' the book by Peter Boghossian that first coined the term Street Epistemology.`,
		},
		{
			term: `A Manual for Creating Atheists`,
			aka: [`AMAFCA`],
			def: `'A Manual for Creating Atheists' the book by Peter Boghossian that first coined the term Street Epistemology.`,
		},
		{
			term: `Rapport`,
			def: `A close and harmonious relationship in which the people or groups concerned understand each other's feelings or ideas and communicate well.`,
		},
		{
			term: `Ontology`,
			aka: [`Ontological`],
			def: ``,
		},
		{
			term: `The Ontology argument`,
			aka: [],
			def: ``,
		},
		{
			term: `Peter Begossian`,
			aka: [],
			def: ``,
		},
		{
			term: `Anthony Magnabosco`,
			aka: [],
			def: ``,
		},
		{
			term: `Christopher Hitchens`,
			aka: [],
			def: ``,
		},
		{
			term: `Sam Harris`,
			aka: [],
			def: ``,
		},
		{
			term: `Heliocentrism`,
			aka: [],
			def: ``,
		},
		{
			term: `Flat earth`,
			aka: [],
			def: ``,
		},
		{
			term: `Critical thinking`,
			def: `The intellectually disciplined process of actively and skilfully conceptualizing, applying, analysing, synthesizing, and/or evaluating information gathered from, or generated by, observation, experience, reflection, reasoning, or communication, as a guide to belief and action.`,
		},
		{
			term: `Street Epistemology`,
			aka: [`SE`],
			def: ``,
		},
		{
			term: `Fallacy`,
			aka: [
				`Fallacies`,
				'Logical fallacy',
				`fallacious thinking`,
				`fallacious reasoning`,
			],
			def: 'Fallacies are common errors in reasoning that will undermine the logic of your argument. Fallacies can be either illegitimate arguments or irrelevant points, and are often identified because they lack evidence that supports their claim.',
		},
		{
			term: `Rational`,
			def: `Based on or in accordance with reason or logic.`,
		},
		{
			term: `Outsider test`,
			aka: ['Outsider test of faith', 'OTF'],
			def: `An outsider test is a tool that can be used to encourage a person to consider how they would feel if someone was using the same reasoning process to support an different claim. This is of used in religious discussion, asking someone to consider if there position could be used by someone of a different faith to support a belief in a different god. .`,
		},
		{
			term: `Doxastic`,
			aka: ['Doxastically open', 'Doxastically closed'],
			def: `A type of logic concerned with reasoning about beliefs. The term doxastically open meaning that you are open to consider alternative positions, and doxastically closed meaning that you are not open to considering new positions. `,
		},
		{
			term: `Deepity`,
			def: `A statement that sounds like it is profound and full of meaning but is actually trivial or meaningless.`,
		},
		{
			term: `Aporia`,
			def: `An expression of doubt. In Street Epistemology this is often a moment where the conversation partner has noticed something important and is reflecting on its the meaning.`,
		},
		{
			term: `Elenchus`,
			def: `In the Socratic method, 'Elenchus' is the question and answer technique that is used to refute an argument.`,
		},
		{
			term: `The null hypothesis`,
			def: ``,
		},
		{
			term: `Ad Hominem`,
			def: ``,
		},
		{
			term: `The Fallacy Fallacy`,
			def: ``,
		},
		{
			term: `Socratic Method`,
			def: `Socratic Method: Named after the philosopher Socrates, this is also known as elenchus. It is the use of questions to probe a point of view, stimulate critical thinking, and evaluate the consistency of ideas.`,
		},
		{
			term: `Apologetics`,
			def: `Not to be confused with 'apology', Apologetics is reasoned arguments or writings in justification of something, typically a theory or religious doctrine.`,
		},
		{
			term: `Woo`,
			aka: [`woo woo`, `spooky thinking`],
			def: `A slang term used to describe pseudoscientific ideas often based on an emotional or irrational reasoning.`,
		},
		{
			term: 'Cognitive bias',
			def: `A cognitive bias is an irrational intuition that can lead us to incorrect evaluations or concussions..`,
		},
		{
			term: `Dunning Kruger Effect`,
			aka: [`Dunning Kruger`],
			def: `A cognitive bias stating that people with low ability at a task overestimate their ability.`,
		},
		{
			term: `Atheism`,
			def: `The absence of belief in the existence of God or gods`,
		},
		{
			term: `Modelling`,
			def: ``,
		},
		{
			term: `Mirroring`,
			def: ``,
		},
		{
			term: `Agnostic`,
			def: `A person who believes that a position on a topic is unreasonable  unknown or can be known of the existence or nature of God.`,
		},
		{
			term: `Presuppositionalism`,
			aka: [`Presup`],
			def: ``,
		},
		{
			term: `Sagan's Standard`,
			aka: [`Extraordinary claims require Extraordinary elements`],
			def: ``,
		},
		{
			term: `Charity interpretation`,
			aka: [],
			def: ``,
		},
		{
			term: `Steel Man`,
			aka: [],
			def: ``,
		},
		{
			term: `Straw Man`,
			aka: [],
			def: ``,
		},
		{
			term: `Cognitive dissonance`,
			aka: [],
			def: ``,
		},
		{
			term: `Active Listening`,
			aka: [],
			def: ``,
		},
		{
			term: `Okhams rassor`,
			aka: [`principle of parsimony`],
			def: ``,
		},
		{
			term: `Hume's guillotine`,
			def: ``,
		},
		{
			term: `Last Thursdayism`,
			aka: [`Omphalos hypothesis`],
			def: ``,
		},
		{
			term: `Cogito, ergo sum`,
			def: ``,
		},
		{
			term: `The Trolley problem`,
			def: ``,
		},
		{
			term: `Free Will`,
			def: ``,
		},
		{
			term: `Nihilism`,
			def: ``,
		},
		{
			term: `Cognitive behaviour therapy`,
			def: ``,
		},
		{
			term: `Confidence scale`,
			def: ``,
		},
		{
			term: `Principle of charity`,
			def: ``,
		},
		{
			term: `Russell's teapot`,
			def: ``,
		},
		{
			term: `Objective / Subjective`,
			def: ``,
		},
		{
			term: `Whatabout'ism`,
			def: ``,
		},
		{
			term: `Compatibilism`,
			def: ``,
		},
		{
			term: `Scepticism`,
			def: ``,
		},
		{
			term: `Cynicism`,
			def: ``,
		},
		{
			term: `The Illusion of Explanatory Depth`,
			def: ``,
		},
		{
			term: `Meta-cognition`,
			def: ``,
		},
		{
			term: `The Backfire effect`,
			def: ``,
		},
		{
			term: `Rapoport’s Rules of Criticism`,
			def: ``,
		},
	]

	// Create the display data, filtering if needed

	const termInString = (searchString: string, sourceString: string) => {
		searchString = searchString.toString().toLowerCase()
		sourceString = sourceString.toString().toLowerCase()
		const searchStringIndex = sourceString.indexOf(searchString)

		return searchStringIndex > -1
	}

	const data = filter
		? glossaryArray.filter((item) => {
				// Search main term
				if (termInString(filter, item.term)) {
					return true
				}

				// Search AKA terms
				return item?.aka?.some((akaItem) =>
					termInString(filter, akaItem)
				)
		  })
		: glossaryArray

	// Alphabetical sort by term

	data.sort((a, b) => {
		if (a.term > b.term) {
			return 1
		}
		if (a.term < b.term) {
			return -1
		}
		return 0
	})

	const highlightTerm = (termToHighlight: string, inString: string) => {
		const parts = inString.split(new RegExp(`(${termToHighlight})`, 'gi'))

		return parts.map((part, i) => {
			if (part.toLowerCase() === termToHighlight.toLowerCase()) {
				return (
					<span key={i} className={style.termToHighlight}>
						{part}
					</span>
				)
			}

			return part
		})
	}

	return (
		<Page className={rootClassName}>
			<PageHeader
				sectionHeading='Street Epistemology Resources'
				heading='Glossary of terms'
			/>

			<div className={style.productFilter}>
				<label htmlFor='filter-text'>Find term</label>
				<input
					id='filter-text'
					name='filter-text'
					onChange={handelInputChange}
					placeholder='Enter your search here'
					type='text'
				/>
			</div>

			<main>
				<dl>
					{data.map((term) => (
						<>
							<dt>
								{highlightTerm(filter, term.term)}

								{term.aka && (
									<ul>
										{term.aka.map((akaTerm) => (
											<li>
												{highlightTerm(filter, akaTerm)}
											</li>
										))}
									</ul>
								)}
							</dt>

							<dd>{term.def}</dd>
						</>
					))}
				</dl>
			</main>
		</Page>
	)
}

export default IndexPage
